language: elixir
cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build
matrix:
  include:
    - otp_release: 21.3
      elixir: 1.9
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 19.0
      elixir: 1.4
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
env:
  - MIX_ENV=test
script:
  - mix compile --warnings-as-errors
  - mix format --check-formatted --dry-run
  - mix coveralls.travis
  - mix dialyzer --halt-exit-status
after_script:
  - mix inch.report
before_cache:
  - mix deps.clean --all --build
  - mix clean --build
cache:
  directories:
    - _build
    - deps
